// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config } from "dotenv";
import { defineConfig } from "prisma/config";

// Prefer .env over stale shell env (e.g. old DIRECT_URL from a previous session)
config({ override: true });

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    // Prisma CLI (migrate, db push) uses direct connection; app runtime uses DATABASE_URL pooler
    url: process.env["DIRECT_URL"],
  },
});
