-- CreateEnum
CREATE TYPE "Role" AS ENUM ('MANAGING_DIRECTOR', 'PROGRAMME_MANAGER', 'ACCOUNTS_SETTLEMENTS_MANAGER', 'FIELD_OPERATIONS_MANAGER', 'ACCOUNTS_SEEDS_SUPPLY_MANAGER', 'LOGISTICS_EXECUTIVE', 'FIELD_OFFICER', 'USER');

-- AlterTable
ALTER TABLE "user" ADD COLUMN     "role" "Role" NOT NULL DEFAULT 'USER',
ADD COLUMN     "stationId" TEXT;

-- CreateIndex
CREATE INDEX "user_stationId_idx" ON "user"("stationId");

-- AddForeignKey
ALTER TABLE "user" ADD CONSTRAINT "user_stationId_fkey" FOREIGN KEY ("stationId") REFERENCES "station"("id") ON DELETE SET NULL ON UPDATE CASCADE;
